Through many years in the software business, I've done kernel and back end development, training, standards, consulting, authoring, people and project managing and more.

I'm currently a core developer on the `SCons project <https://github.com/SCons/scons>`_, if you want to see some of my recent Python work.

If anyone would like help with community building or developer advocacy type activities, feel free to reach out.

You can catch me as `@mdwichmann` on Twitter and `@mdwichmann@mastodon.social`.
